version: '3.5'

services:
  management-center:
    image: hazelcast/management-center:3.10.2
    ports:
      - 9080:8080
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      backend:

  proven:
    image: gridappsd/proven:v2019.03.0
    deploy:
      replicas: 2
    ports:
      - 18080:8080
    environment:
      # PROVEN_SERVICES_PORT - Proven service port [18080]
      # PROVEN_SWAGGER_HOST_PORT - Host and port value for Swagger (<host>:<port>)
      # PROVEN_USE_IDB - Use InfluxDB to save provenance metrics (true | false) [false]
      # PROVEN_IDB_URL - InfluxDB URL [http://localhost:8086]
      # PROVEN_IDB_DB - InfluxDB Database [proven]
      # PROVEN_IDB_RP - InfluxDB retention policy [autogen]
      # PROVEN_IDB_USERNAME - InfluxDb username [root]
      # PROVEN_IDB_PASSWORD - InfluxDb password [root]
      # PROVEN_T3DIR - directory location of triple store [user_home_directory]
      ####
      - PROVEN_SERVICES_PORT=18080
      - PROVEN_SWAGGER_HOST_PORT=localhost:18080
      - PROVEN_USE_IDB=true
      - PROVEN_IDB_URL=http://influxdb:8086
      - PROVEN_IDB_DB=proven
      - PROVEN_IDB_RP=autogen
      - PROVEN_IDB_USERNAME=root
      - PROVEN_IDB_PASSWORD=root
      - PROVEN_T3DIR=/proven
    volumes:
      - ./hazelcast-proven-data.xml:/opt/payara/deployments/hazelcast-proven-data.xml
      - ./proven-system-properties:/opt/payara/deployments/proven-system-properties
    links:
      - "management-center:hazelcast-mancenter"
    networks:
      - backend

  influxdb:
    image: gridappsd/influxdb:v2019.03.0
    environment:
      INFLUXDB_DB: "proven"
    ports:
      - 8086:8086
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - backend

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

